[workspace]
resolver = "3"

members = ["cli", "onyx", "common"]

[workspace.dependencies]
anyhow = "1.0.98"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.45.1", features = ["full"] }
blake3 = "1.8.2"
tar = "0.4.44"
tempfile = "3.20.0"
