[workspace]
resolver = "3"

members = ["cli", "onyx"]

[workspace.dependencies]
anyhow = { version = "1.0.98" }
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.45.1", features = ["full"] }
