[package]
name = "cli"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[[bin]]
name = "nrpm"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }

clap = "4.5.40"
ignore = "0.4.23"
blake3 = "1.8.2"
flume = "0.11.1"
tar = "0.4.44"
tempfile = "3.20.0"
