[package]
name = "cli"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[[bin]]
name = "nrpm"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
blake3 = { workspace = true }
tar = { workspace = true }
tempfile = { workspace = true }
reqwest = { workspace = true }
nanoid = { workspace = true }

onyx_api = { path = "../onyx_api", features = ["publish"] }
tarball = { path = "../tarball" }

clap = "4.5.40"
dialoguer = "0.11.0"
open = "5.3.2"
