[package]
name = "web"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
reqwest = { workspace = true }

dioxus = "0.6.3"
serde_json = "1.0.140"
dioxus-web = "0.6.3"

[dependencies.web-sys]
version = "0.3"
features = ["console"]
